---
title: "GISAID Ingest Pipeline for C.3 Reassortment Analysis"
author: Elgin Akin
date: 05-10-2025
format: html
---

The purpose of this data ingest pipeline to in take GISAID sequences and metadata files for santizing, de-duplicating and fomatting to input into a standard Nextstrain 8 segment and concatenated genome build pipeline.

# Download sequences from GISAID

Updated 4/2/2026
- In order to gain more accurate summation of subclade frequency over time, I switched GISAID filtering to require only a cmplete HA sequence. Because GISAID restricts users to 20,000 sequences at a time, we will break up our downloads into 2 datasets. Set A which will encompass sequences between 2020-10-01 – 2025-01-01 and Set B which will capture all sequences uploaded between 2025-01-02 and 202X-XX-XX updating to the most recently desired dataset. This is a critical change since many health departments and other sequencing entities do not perform whole genome sequencing (e.g. Most B/Sydney sequences are HA and NA only). 

Instruction for downloading data from GISAID 
    - Total GISAID filters when downloading include: 
        - Type: B
        - Collection Date: 
            - Reference Set A: 2020-10-01 – 2025-01-01
            - Reference Set B: 2025-01-02 - 2026-04-01 OR the most recent desired dataset
        - Collection Date: Complete
        - GISRS Submission Selected
        - Required Segments: HA
        - Passage Details/History
        - Only Complete
        - Nucleotide FASTA Defline: `Isolate ID | Virus name |  Segment  | Type`


Sequences and corresponding metadata files should be named using the following schema: 
    Sequence file names: 
        - Set A: seta_gisaid_vic_sequences.fasta
        - Set B: setb_gisaid_vic_sequences.fasta
    Metadata file names
        - Set A: seta_gisaid_vic_metadata.xls
        - Set B: setb_gisaid_vic_metadata.xls

## Updated Sequence EPI Set iterations

Local Snapshot Addendum Logs
1. 20260318 - Included sequences collected up to Feb 1st 2026
    - EPI_SET_260225ya, https://doi.org/10.55876/gis8.260225ya

2. 20260318 - New dataset includes sequences uploaded to nextstrain up to March 18, 2026 to include novel C.3 reassortments.
    - Date Range: 2020-02-01 to 2026-03-18
    - Filters: Type B, Collection date (2020-02-01 to 2026-03-18), Required segments (all), Passage details/history = original, Only complete. 
    - fasta defline  `Isolate ID | Virus name |  Segment  | Type`
    -  EPI_Set EPI_SET_260318et, https://doi.org/10.55876/gis8.260318et

3. 20260402 Updating to capture all HA sequences 
        - Reference Set A: 2020-10-01 – 2025-01-01
        - Reference Set B: 2025-01-02 - 2026-04-01 OR the most recent desired dataset   

        - Set A:  EPI_SET_260402ha, https://doi.org/10.55876/gis8.260402ha 
            (use in all future iterations) is now stored at
        - Set B: 

```{shell}
conda activate ibvc3 
```

## Activate
```{shell}
#| eval: false
python fludb/scripts/fludb_initiate.py
```


# Data Ingest 

## concatenate Set A and Set B FASTA Datasets



## Bind Set A and Set B metadata 

```{shell}

```


### Pull strains and check for embargos

```{shell}

```
## Remove sequences with ambiguous nucleotide calls and deduplicate with SeqKit
```{shell}
# ibv victoria (vic)
seqkit rmdup -n source/gisaid_vic_sequences.fasta > source/gisaid_vic_sequences.rmdup.fasta
seqkit grep -s -r -i -p "^[ATCGatcg]+$" source/gisaid_vic_sequences.rmdup.fasta > source/gisaid_vic_sequences.rmdupn.noambig.fasta
```




## Upload CEIRR and GISAID sequences to fludb

### Upload JH-CEIRR (Johns Hopkins Hospital - JHH formatted) sequences and metadata
```{shell}
#| eval: false
python fludb/scripts/upload_jhh.py \
    -d fludb.db \
    -f source/flusort_JHH_sequences.fasta \
    -m source/flusort_JHH_metadata.tsv \
    --require-sequence
```

### Upload vaccines strains

- [ ] Include B/Austria into `include.tsv`

```{shell}
#| eval: false
python fludb/scripts/upload_vaccine.py \
    -d fludb.db \
    -f source/vaccine.fasta
```

### Upload all GISAID strains 

```{shell}
#python fludb/scripts/upload_gisaid.py \
#    -d fludb.db \
#    -f source/gisaid_vic_sequences.rmdupn.noambig.fasta \
#    -m source/gisaid_vic_metadata.xls 
```

USE THIS SCRIPT _ TEST A SANITIZED VERSION LATER

GISAID FASTA defline (header) should be in the following format: 
- gisaid_accession | strain | segment_name | type
- e.g. EPI_ISL_18743008|B/Sao_Paulo/357274094-IAL/2023|PB2|B
```{shell}
python fludb/scripts/upload_gisaid_sanitize.py \
    -d fludb.db \
    -f source/gisaid_vic_sequences.rmdupn.noambig.fasta \
    -m source/gisaid_vic_metadata.xls \
    --sanitize-names \
    --remove-duplicate-strains
```


### Download all complete influenza genomes

```{shell}
#| eval: false
# downloads genomes
python scripts/fludb_download_genomes.py
# download all 8 segments 
python scripts/fludb_download_segments.py
```

# Run nextclade on all segments and extract clades, glycosylation and qc metrics 

For each segment (pb2, pb1, pa, ha, np, na, mp, ns):

1. Run Nextclade
Generates nextclade.tsv from segment FASTA files using the appropriate Nextclade dataset.

2. Extract Key Fields
From each segment’s nextclade.tsv, extract:
qc.overallScore, qc.overallStatus, coverage → renamed with segment prefix (e.g., pb2_qc.overallScore)
For ha: also extract clade, subclade, and glycosylation
For na: also extract glycosylation

3. Merge Segment QC into a Genome Table
Combines all segment-level QC and annotation into a single table.
Computes:
    genome_qc.overallScore → average of all segment scores
    genome_qc.overallStatus → semicolon-delimited string of statuses (e.g., pb2:good;pa:bad;...)

4. Update Metadata Files
    Merges relevant QC fields into each segment’s and the genome’s metadata.tsv
    Uses sample_ID (from metadata) matched to seqName (from Nextclade)
    Saves enriched files as metadata_qc.tsv

output: 
- nextclade.tsv per segment
- Merged genome_qc_summary.tsv
- QC-enriched metadata_qc.tsv for each segment and genome

```{shell}
python scripts/nextclade_segment_qc.py
```

new output metadata for each segment is `metadata_qc.tsv`

# Downsampling from the HA dataset (since now we have everything we need to downsample in the ha dataset)

1. Expand the `location` column in HA metadata. - we'll focus on region and country.
2. de-duplicate the metadata file by the sample_ID (this will automatically filter out any fasta entry not present in the metadata)
3. de-duplicate the nextclade file by the sample_ID (this will automatically filter out any fasta entry not present in the metadata)
4. Left join HA nextclade result file with fludb metadata file 
5. Enrich C.3s by Downsample gisaid HA for C.3 sequences - obtain fasta headers 
6. Downsample all non-C.3 gisaid isolates
7. Extract all high genome quality JHH Isolates
8. Final representative strains for each segment - ingest into data/ folder
9. Drop Clade and Subclade columns for final filtering
10. Loop through all segments and the genome dataset to extract curated + downsampled sequences

## 1. Expand the `location` column in HA metadata. - we'll focus on region and country. 

LOOP - Function to extract region, country, and division from an original location column

```{shell}
# we dont need the loop for now but wrote it just in case...
python scripts/loop_format-location.py
```

resulting file is source/intermediate/vic/ha/metadata_qc_location.tsv

## 2. de-duplicate the metadata file by the sample_ID (this will automatically filter out any fasta entry not present in the metadata)

```{shell}
python scripts/dedup.py \
    -i source/intermediate/vic/ha/metadata_qc_location.tsv \
    -o source/intermediate/vic/ha/metadata_qc_location_dedup.tsv \
    -d logs/metadata_duplicates.tsv \
    --drop-all-duplicates \
    -c "sample_ID"
```

# 3. de-duplicate the nextclade file by the sample_ID (this will automatically filter out any fasta entry not present in the metadata)

```{shell}
python scripts/dedup.py \
    -i source/intermediate/vic/ha/nextclade.tsv \
    -o source/intermediate/vic/ha/nextclade_dedup.tsv \
    -d logs/metadata_duplicates.tsv \
    --drop-all-duplicates \
    -c "seqName"
```

## 4. Left join HA nextclade result file with fludb metadata file 

We'll now stick with just curating the HA sequence metadata 

```{shell}
csvtk -t join -f "sample_ID;seqName" \
    source/intermediate/vic/ha/metadata_qc_location_dedup.tsv \
    <(csvtk -t cut -f seqName,clade,subclade source/intermediate/vic/ha/nextclade_dedup.tsv) \
    --left-join \
    > source/intermediate/vic/ha/metadata_qc_location_clades_dedup_clades.tsv

```

## 5. Enrich C.3s by Downsample gisaid HA for C.3.X lineaged sequences - obtain fasta headers

result: gisaid (non JHH) downsample of all C.3s with high quality genomes. This pulls ALL C.3s assigned by nextclade into the build thereby enriching parental C.3s.

As of 3/18/2026, we've decided to enrich for C.3, C.3.1, and the very very minor C.3.2 lineage.

```{shell}
augur filter \
    --metadata source/intermediate/vic/ha/metadata_qc_location_clades_dedup_clades.tsv \
    --sequences source/intermediate/vic/ha/sequences.fasta \
    --metadata-id-columns "sample_ID" \
    --exclude-where "area=Baltimore" \
    --exclude config/exclude.tsv \
    --query '(subclade == "C.3" | subclade == "C.3.1" | subclade == "C.3.2") and (`genome_qc.overallStatus` == "pb2:good;pb1:good;pa:good;ha:good;np:good;na:good;mp:good;ns:good")' \
    --output-strains config/vic/include_c3.tsv
```

## 6. Down-select all gisaid isolates

2025-06-28 - Update criteria to include C.3s in the augur down-selection. Remove "subclade=C.3" 

Formerly included all known C.3 HA:NA reassortments

Vaccine strains

```{shell}
augur filter \
    --metadata source/intermediate/vic/ha/metadata_qc_location_clades_dedup_clades.tsv \
    --sequences source/intermediate/vic/ha/sequences.fasta \
    --metadata-id-columns "sample_ID" \
    --exclude-where "area=Baltimore" \
    --exclude config/exclude.tsv \
    --query '(`genome_qc.overallStatus` == "pb2:good;pb1:good;pa:good;ha:good;np:good;na:good;mp:good;ns:good")' \
    --group-by week country \
    --subsample-max-sequences 2000 \
    --subsample-seed 180 \
    --output-strains config/vic/include_gisaid.tsv
```

## 7. Extract all high genome quality JHH Isolates

```{shell}
augur filter \
    --metadata source/intermediate/vic/ha/metadata_qc_location_clades_dedup_clades.tsv \
    --sequences source/intermediate/vic/ha/sequences.fasta \
    --metadata-id-columns "sample_ID" \
    --exclude-where "region!=JHH" \
    --exclude config/exclude.tsv \
    --query '(`genome_qc.overallStatus` == "pb2:good;pb1:good;pa:good;ha:good;np:good;na:good;mp:good;ns:good")' \
    --output-strains config/vic/include_JHH.tsv
```

## 9. Drop Clade and Subclade columns for final filtering

in: source/intermediate/vic/ha/metadata_qc_location_clades_dedup_clades.tsv
out: source/intermediate/vic/ha/metadata_final.tsv

```{shell}
csvtk cut -t -f -clade,-subclade \
    source/intermediate/vic/ha/metadata_qc_location_clades_dedup_clades.tsv \
    > source/intermediate/vic/ha/metadata_final.tsv
```

## 10. Loop through all segments and the genome dataset to extract curated + downsampled sequences
```{shell}
python scripts/curate-segments.py
```

Note because we used subclade for downsample, all metadata files have clade and subclade thus we can remove it from the segments pipeline. 
may need to 
1. update nextclade datasets manually
2. Remove clade assignment from either snakemake pipeline or the metadata (meatadata may be easier...)

# Manual Inspection of data/ sequences

```
seqkit stats data/**/*.fasta 
```

```
bioawk -c fastx '(length($seq) <  1000) { print ">"$name"\n"$seq }' data/vic/pb1/sequences.fasta
```

# Proceed with running the core seasonal pipeline 

```{shell}
snakemake --cores 8
```

Visualizing subclade richness in the following datasets:

- JHH only 
- GISAID total 
- GISAID + JHH
- final downsampled + C.3 enriched 


# Changelog

- 20250818: Resolve NA and NS polytomies by broadly adding `iqtree -s {alignment} -B 1000 -alrt 1000 -T AUTO` 