#!/usr/bin/env python3
"""
bind_metadata.py

CLI tool to bind (concatenate) multiple Excel metadata files with the same column names
into a single output Excel file.

Usage examples:
  python bind_metadata.py -i file1.xlsx file2.xlsx file3.xlsx -o combined.xlsx
  python bind_metadata.py -i *.xls -o output.xlsx
  python bind_metadata.py --input data1.xlsx data2.xlsx --output merged.xlsx

Features:
  - Accepts multiple Excel files (.xls or .xlsx) via -i/--input flag.
  - Concatenates all rows, preserving column order from the first file.
  - Handles missing columns gracefully (fills with NaN).
  - Outputs a single Excel file specified by -o/--output.
  - Optional -s/--sheet flag to specify which sheet to read from each file (default: first sheet).

Requirements:
  - Python 3.6+
  - pandas
  - openpyxl (for .xlsx files): pip install openpyxl
  - xlrd==1.2.0 (for legacy .xls files): pip install xlrd==1.2.0

Author: Generated by AI assistant
"""

import argparse
import os
import sys

try:
    import pandas as pd
except ImportError:
    sys.exit("This script requires pandas. Install with: pip install pandas openpyxl (and xlrd==1.2.0 for legacy .xls)")

def parse_args():
    parser = argparse.ArgumentParser(
        prog="bind_metadata.py",
        description=(
            "Bind (concatenate) multiple Excel metadata files with the same column names "
            "into a single output Excel file."
        ),
        epilog=(
            "Examples:\n"
            "  python bind_metadata.py -i file1.xlsx file2.xlsx file3.xlsx -o combined.xlsx\n"
            "  python bind_metadata.py -i *.xls -o output.xlsx\n"
            "  python bind_metadata.py --input data1.xlsx data2.xlsx --sheet Sheet1 --output merged.xlsx\n"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter
    )

    parser.add_argument(
        "-i", "--input", required=True, nargs='+',
        help="One or more input Excel files (.xls or .xlsx) to bind together."
    )
    parser.add_argument(
        "-o", "--output", required=True,
        help="Path to output Excel file (e.g. combined.xlsx)."
    )
    parser.add_argument(
        "-s", "--sheet", default=None,
        help="Optional sheet name or index to read from each file (default: first sheet)."
    )

    return parser.parse_args()

def main():
    args = parse_args()

    input_files = args.input
    output_path = args.output
    sheet_arg = args.sheet

    # Validate input files exist
    for fpath in input_files:
        if not os.path.isfile(fpath):
            sys.exit(f"Input file not found: {fpath}")

    # Prepare pandas read_excel kwargs
    read_kwargs = {}
    if sheet_arg is not None:
        # allow numeric index or name
        try:
            read_kwargs['sheet_name'] = int(sheet_arg)
        except ValueError:
            read_kwargs['sheet_name'] = sheet_arg

    # Read all input files into a list of DataFrames
    dfs = []
    for i, fpath in enumerate(input_files):
        try:
            df = pd.read_excel(fpath, **read_kwargs)
            # Normalize column names: strip whitespace
            df.rename(columns={c: str(c).strip() for c in df.columns}, inplace=True)
            dfs.append(df)
            print(f"Read {len(df)} rows from {fpath}")
        except Exception as e:
            sys.exit(f"Failed to read Excel file '{fpath}': {e}")

    if not dfs:
        sys.exit("No data frames loaded. Please check your input files.")

    # Concatenate all DataFrames
    # sort=False preserves column order from first DataFrame
    # ignore_index=True resets row indices in the combined DataFrame
    try:
        combined_df = pd.concat(dfs, ignore_index=True, sort=False)
    except Exception as e:
        sys.exit(f"Failed to concatenate DataFrames: {e}")

    print(f"\nCombined DataFrame has {len(combined_df)} rows and {len(combined_df.columns)} columns.")

    # Ensure output directory exists
    out_dir = os.path.dirname(os.path.abspath(output_path))
    if out_dir and not os.path.exists(out_dir):
        try:
            os.makedirs(out_dir, exist_ok=True)
        except Exception as e:
            sys.exit(f"Failed to create output directory '{out_dir}': {e}")

    # Write to Excel
    try:
        combined_df.to_excel(output_path, index=False, engine='openpyxl')
    except Exception as e:
        sys.exit(f"Failed to write output file '{output_path}': {e}")

    print(f"Successfully wrote combined data to {output_path}")

if __name__ == "__main__":
    main()