---
title: "GISAID Ingest Pipeline for C.3 Reassortment Analysis"
author: Elgin Akin
date: 05-10-2025
format: html
---

The purpose of this data ingest pipeline to in take GISAID sequences and metadata files for santizing, de-duplicating and fomatting to input into a standard Nextstrain 8 segment and concatenated genome build pipeline.


```{shell}
conda activate flu
```

## Activate
```{shell}
#| eval: false
python fludb/scripts/fludb_initiate.py
```

# Data Ingest 

```{shell}
# ibv victoria (vic)
seqkit rmdup -n source/gisaid_vic_sequences.fasta > source/gisaid_vic_sequences.rmdup.fasta
seqkit grep -s -r -i -p "^[ATCGatcg]+$" source/gisaid_vic_sequences.rmdup.fasta > source/gisaid_vic_sequences.rmdupn.noambig.fasta
```

## Upload CEIRR and GISAID sequences to fludb

### Initiate

### CIERR JHH 
```{shell}
#| eval: false
python fludb/scripts/upload_jhh.py \
    -d fludb.db \
    -f source/flusort_JHH_sequences.fasta \
    -m source/flusort_JHH_metadata.tsv \
    --require-sequence
```

### Vaccines 

```{shell}
#| eval: false
python fludb/scripts/upload_vaccine.py \
    -d fludb.db \
    -f source/vaccine.fasta
```

```{shell}
python fludb/scripts/upload_gisaid.py \
    -d fludb.db \
    -f source/gisaid_vic_sequences.rmdupn.noambig.fasta \
    -m source/gisaid_vic_metadata.xls
```

### Download all complete influenza genomes

```{shell}
#| eval: false
# downloads genomes
python scripts/fludb_download_seasonal_build_genomes.py
# download all 8 segments 
python scripts/fludb_download_seasonal_build.py
```

# nextclade ha 

```{shell}
nextclade run \
    -D nextclade/flu/vic/ha/ \
    -t results/vic/ha/nextclade.tsv \
    -o results/vic/ha/nextclade_aligned.fasta \
    data/vic/ha/sequences.fasta
```

# Downsampling 

1. Downsample HA C.3 sequences - obtain fasta headers
2. Downsample HA probableistic - obtain fasta headers
3. Use both include.tsv files to go back to 


## Expand the `location` column in HA metadata to house continent and country in 2 seperate columns. Ignore levels 3 and 4 in location column as most rows do not have this information.

TODO: can we rewrite this with csvtk to be more streamlined? 

Function to extract region, country, and division from 

```{python}
import pandas as pd

def split_location(df, location_col="location", sequence_id_col="sequence_ID", sample_id_col="sample_ID"):
    """
    Enhances a metadata dataframe by splitting the location column and creating a strain column.

    Parameters:
        df (pd.DataFrame): Input DataFrame.
        location_col (str): Name of the column to split by " / ".
        sequence_id_col (str): Name of the sequence ID column.
        sample_id_col (str): Name of the sample ID column.

    Returns:
        pd.DataFrame: Enhanced DataFrame with added region, country, division, location_detailed, and strain columns.
    """

    def extract_levels(row, level):
        if isinstance(row, str):
            parts = row.split(" / ")
            return parts[level] if len(parts) > level else None
        return None

    # Apply location splitting
    df["region"] = df[location_col].apply(lambda x: extract_levels(x, 0))
    df["country"] = df[location_col].apply(lambda x: extract_levels(x, 1))
    df["division"] = df[location_col].apply(lambda x: extract_levels(x, 2))
    df["location_detailed"] = df[location_col].apply(lambda x: extract_levels(x, 3))

    # Create strain column
    df["strain"] = df[sequence_id_col].astype(str) + "_" + df[sample_id_col].astype(str)


    return df

h1n1_locations = pd.read_csv("../data/h1n1/genome/metadata.tsv", delimiter="\t")
h3n2_locations = pd.read_csv("../data/h3n2/genome/metadata.tsv", delimiter="\t")
vic_locations = pd.read_csv("../data/vic/genome/metadata.tsv", delimiter="\t")

h1n1_locations = split_location(h1n1_locations)
h3n2_locations = split_location(h3n2_locations) 
vic_locations = split_location(vic_locations) 

h1n1_locations.to_csv("../results/h1n1/genome/metadata.tsv", sep = "\t", index = False)
h3n2_locations.to_csv("../results/h3n2/genome/metadata.tsv", sep = "\t", index = False)
vic_locations.to_csv("../results/vic/genome/metadata.tsv", sep = "\t", index = False)

```

```{shell}

augur filter \
    --metadata results/vic/ha/metadata.tsv\
    --sequences data/vic/ha/sequences.fasta \
    --min-length 13000 \
    --metadata-id-columns "sample_ID" \
    --exclude-all \
    --group-by week country \
    --subsample-max-sequences 2000 \
    --subsample-seed 180 \
    --output-metadata results/h1n1/genome/gisaid_filtered.tsv \
    --output-sequences results/h1n1/genome/gisaid_filtered.fasta

```